# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0235_userprofile_desktop_icon_count_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_list_content',
            field=models.CharField(choices=[('all', 'All users'), ('member', 'Stream or PM recipients')], default='all', max_length=10),
        ),
    ]
