# Generated by Django 3.2.11 on 2022-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0376_set_realmemoji_author_and_reupload_realmemoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="emoji_animation_config",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emoji_animation_config",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
